### ISSUE TITLE
Invalid sources are detected when using basic suggested setup

### ISSUE THREAD

**Issue by jeffwillette** [Shougo/ddc-source-omni#2] opened 2022-04-21 01:07 UTC
NVIM: NVIM v0.7.0-dev+1254-g6dc2c8293
denops: d01a89773b158255073cefa88f6527fb9f522e59
ddc: a2ee2f7e70fbd1a5e093e733e108183fc4cffafb
ddc-omni: 5bc143c192aeca2aefce5cc8b104b6dc55333190

When using these versions with the basic suggested setup, I get the following error from vim when I add the omni source. It does not give an error on startup, but only after some completion has been triggered.

```
[ddc] Invalid sources are detected!
[ddc] ['omni']
```

**Comment by Shougo** [comment] 2022-04-21 01:22
Please upload the minimal vimrc and the reproduce instructions.
I cannot reproduce the problem.

Note: unfortunately, I need to close the issue without the information.

**Comment by Shougo** [comment] 2022-04-21 01:23
> When using these versions with the basic suggested setup, 

The basic suggested setup no means for me.
If you get the information from customer, can you fix the problem?

**Comment by Shougo** [comment] 2022-04-21 01:31
Hm....  I get the problem.  The source is too old and does not support the latest ddc.

**Closed as completed** 2022-04-21 03:29 UTC
Labels: bug

**Comment by Shougo** [comment] 2022-04-21 03:30
Fixed.
